version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install Jinja2 PyYAML

  build:
    commands:
      - echo "Rendering CloudFormation templates..."
      - python render.py
      - echo "Deploying stacks..."
      - |
        for file in output/*.yaml; do
          stack_name=$(basename "$file" .yaml | sed 's/lambda-eb-//')
          aws cloudformation deploy \
            --template-file "$file" \
            --stack-name "lambda-eb-${stack_name}" \
            --capabilities CAPABILITY_NAMED_IAM
        done